
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AngleUnit", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/ConvertAngle.asmx?WSDL")
public class AngleUnit
    extends Service
{

    private final static URL ANGLEUNIT_WSDL_LOCATION;
    private final static WebServiceException ANGLEUNIT_EXCEPTION;
    private final static QName ANGLEUNIT_QNAME = new QName("http://www.webserviceX.NET/", "AngleUnit");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/ConvertAngle.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANGLEUNIT_WSDL_LOCATION = url;
        ANGLEUNIT_EXCEPTION = e;
    }

    public AngleUnit() {
        super(__getWsdlLocation(), ANGLEUNIT_QNAME);
    }

    public AngleUnit(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANGLEUNIT_QNAME, features);
    }

    public AngleUnit(URL wsdlLocation) {
        super(wsdlLocation, ANGLEUNIT_QNAME);
    }

    public AngleUnit(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANGLEUNIT_QNAME, features);
    }

    public AngleUnit(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AngleUnit(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AngleUnitSoap
     */
    @WebEndpoint(name = "AngleUnitSoap")
    public AngleUnitSoap getAngleUnitSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET/", "AngleUnitSoap"), AngleUnitSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AngleUnitSoap
     */
    @WebEndpoint(name = "AngleUnitSoap")
    public AngleUnitSoap getAngleUnitSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET/", "AngleUnitSoap"), AngleUnitSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANGLEUNIT_EXCEPTION!= null) {
            throw ANGLEUNIT_EXCEPTION;
        }
        return ANGLEUNIT_WSDL_LOCATION;
    }

}
