
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AngleUnitSoap", targetNamespace = "http://www.webserviceX.NET/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AngleUnitSoap {


    /**
     * 
     * @param fromAngleUnit
     * @param angleValue
     * @param toAngleUnit
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ChangeAngleUnit", action = "http://www.webserviceX.NET/ChangeAngleUnit")
    @WebResult(name = "ChangeAngleUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    @RequestWrapper(localName = "ChangeAngleUnit", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeAngleUnit")
    @ResponseWrapper(localName = "ChangeAngleUnitResponse", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeAngleUnitResponse")
    public double changeAngleUnit(
        @WebParam(name = "AngleValue", targetNamespace = "http://www.webserviceX.NET/")
        double angleValue,
        @WebParam(name = "fromAngleUnit", targetNamespace = "http://www.webserviceX.NET/")
        Angles fromAngleUnit,
        @WebParam(name = "toAngleUnit", targetNamespace = "http://www.webserviceX.NET/")
        Angles toAngleUnit);

}
